import { EnableImageWatermark } from "../interface/config/enable.image.watermark";
import { BucketConfig } from "../interface/config/bucket.config";
import { AudioFormat } from "../interface/config/audio.format";
import { ImageFormat } from "../interface/config/image.format";
import { VideoFormat } from "../interface/config/video.format";
import { ImageProcessUtil } from "../util/image.process.util";
import { AudioConfig } from "../model/audio.config.entity";
import { ImageConfig } from "../model/image.config.entity";
import { VideoConfig } from "../model/video.config.entity";
import { Bucket } from "../model/bucket.entity";
import { Image } from "../model/image.entity";
import { FileUtil } from "../util/file.util";
import { Repository } from "typeorm";
export declare class ConfigService {
    private readonly fileUtil;
    private readonly imageProcessUtil;
    private readonly imageRepository;
    private readonly bucketRepository;
    private readonly imageConfigRepository;
    private readonly audioConfigRepository;
    private readonly videoConfigRepository;
    private readonly baseDirectory;
    constructor(fileUtil: FileUtil, imageProcessUtil: ImageProcessUtil, imageRepository: Repository<Image>, bucketRepository: Repository<Bucket>, imageConfigRepository: Repository<ImageConfig>, audioConfigRepository: Repository<AudioConfig>, videoConfigRepository: Repository<VideoConfig>);
    saveBucketConfig(body: BucketConfig): Promise<void>;
    saveImageFormat(body: ImageFormat): Promise<void>;
    saveEnableImageWatermark(body: EnableImageWatermark): Promise<void>;
    saveImageWatermark(file: any, obj: any): Promise<void>;
    saveAudioFormat(body: AudioFormat): Promise<any>;
    saveVideoFormat(body: VideoFormat): Promise<any>;
}
